### ISSUE TITLE
Структура и оформление репозитория

### ISSUE THREAD

**Issue by Stasenko-Konstantin** [Pokulord/PyProjects#1]
Привет! Прости что лезу с советами, но мне и другим будет удобнее смотреть на что то более структурированное что ли. 
В общем советую глянуть как писать README.md (markdown) и разложить все, ну или почти все, по своим папкам. 
Например можешь глянуть мой [репозиторий](https://github.com/Stasenko-Konstantin/old_go_projects), там в каждой папке есть README.md, например:

![изображение](https://user-images.githubusercontent.com/58981694/182215162-5ffe1077-0cba-4050-982a-ba420e6958b4.png)
![изображение](https://user-images.githubusercontent.com/58981694/182215641-561f01fb-ea11-4761-9fac-86a6d0b3ed28.png)

**Comment by Pokulord** [comment]
Благодарю за совет. Это мой первый опыт пользования "GitHub" - ом и любая
информация будет кстати.

пн, 1 авг. 2022 г., 23:42 Стасенко Константин ***@***.***>:
